# Generated by Django 3.2.9 on 2021-12-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
